/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *backspace;
  GtkWidget *CE;
  GtkWidget *clear;
  GtkWidget *seven;
  GtkWidget *eight;
  GtkWidget *nine;
  GtkWidget *four;
  GtkWidget *five;
  GtkWidget *six;
  GtkWidget *one;
  GtkWidget *two;
  GtkWidget *three;
  GtkWidget *zero;
  GtkWidget *equal;
  GtkWidget *addition;
  GtkWidget *multiplication;
  GtkWidget *division;
  GtkWidget *substraction;
  GtkWidget *dot;
  GtkWidget *negative;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 136, 48);
  gtk_widget_set_size_request (entry1, 248, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  backspace = gtk_button_new_with_mnemonic (_("backspc"));
  gtk_widget_show (backspace);
  gtk_fixed_put (GTK_FIXED (fixed1), backspace, 40, 168);
  gtk_widget_set_size_request (backspace, 70, 29);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed1), CE, 168, 168);
  gtk_widget_set_size_request (CE, 69, 29);

  clear = gtk_button_new_with_mnemonic (_("clear"));
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed1), clear, 288, 168);
  gtk_widget_set_size_request (clear, 70, 29);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed1), seven, 40, 232);
  gtk_widget_set_size_request (seven, 70, 29);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 168, 232);
  gtk_widget_set_size_request (eight, 70, 29);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 288, 232);
  gtk_widget_set_size_request (nine, 70, 29);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 40, 296);
  gtk_widget_set_size_request (four, 70, 29);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 168, 296);
  gtk_widget_set_size_request (five, 79, 29);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 288, 296);
  gtk_widget_set_size_request (six, 79, 29);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 40, 360);
  gtk_widget_set_size_request (one, 79, 29);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 168, 360);
  gtk_widget_set_size_request (two, 78, 29);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 288, 360);
  gtk_widget_set_size_request (three, 79, 29);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 40, 424);
  gtk_widget_set_size_request (zero, 79, 29);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 288, 424);
  gtk_widget_set_size_request (equal, 79, 29);

  addition = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (addition);
  gtk_fixed_put (GTK_FIXED (fixed1), addition, 408, 424);
  gtk_widget_set_size_request (addition, 78, 29);

  multiplication = gtk_button_new_with_mnemonic (_("*"));
  gtk_widget_show (multiplication);
  gtk_fixed_put (GTK_FIXED (fixed1), multiplication, 408, 296);
  gtk_widget_set_size_request (multiplication, 78, 29);

  division = gtk_button_new_with_mnemonic (_("/"));
  gtk_widget_show (division);
  gtk_fixed_put (GTK_FIXED (fixed1), division, 408, 232);
  gtk_widget_set_size_request (division, 69, 29);

  substraction = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (substraction);
  gtk_fixed_put (GTK_FIXED (fixed1), substraction, 408, 360);
  gtk_widget_set_size_request (substraction, 79, 29);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 168, 424);
  gtk_widget_set_size_request (dot, 78, 29);

  negative = gtk_button_new_from_stock ("+/-");
  gtk_widget_show (negative);
  gtk_fixed_put (GTK_FIXED (fixed1), negative, 408, 168);
  gtk_widget_set_size_request (negative, 69, 29);

  g_signal_connect ((gpointer) backspace, "clicked",
                    G_CALLBACK (on_backspace_clicked),
                    NULL);
  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) addition, "clicked",
                    G_CALLBACK (on_addition_clicked),
                    NULL);
  g_signal_connect ((gpointer) multiplication, "clicked",
                    G_CALLBACK (on_multiplication_clicked),
                    NULL);
  g_signal_connect ((gpointer) division, "clicked",
                    G_CALLBACK (on_division_clicked),
                    NULL);
  g_signal_connect ((gpointer) substraction, "clicked",
                    G_CALLBACK (on_substraction_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) negative, "clicked",
                    G_CALLBACK (on_negative_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, backspace, "backspace");
  GLADE_HOOKUP_OBJECT (window1, CE, "CE");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, seven, "seven");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, addition, "addition");
  GLADE_HOOKUP_OBJECT (window1, multiplication, "multiplication");
  GLADE_HOOKUP_OBJECT (window1, division, "division");
  GLADE_HOOKUP_OBJECT (window1, substraction, "substraction");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, negative, "negative");

  return window1;
}

